language: node_js
sudo: false

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '4'
  - '6'
  - '7'
  - '8'

before_script:
  - npm prune

after_success:
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
