// flow-typed signature: 8d47564adfe5dfa32f8139224d4d7429
// flow-typed version: <<STUB>>/big-number_v^0.4.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'big-number'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'big-number' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'big-number/lib/big-number' {
  declare module.exports: any;
}

declare module 'big-number/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'big-number/index' {
  declare module.exports: $Exports<'big-number'>;
}
declare module 'big-number/index.js' {
  declare module.exports: $Exports<'big-number'>;
}
declare module 'big-number/lib/big-number.js' {
  declare module.exports: $Exports<'big-number/lib/big-number'>;
}
declare module 'big-number/test/test.js' {
  declare module.exports: $Exports<'big-number/test/test'>;
}
